/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.io.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author alexj
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public static int localizador = 0;
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        setIconImage(new ImageIcon(getClass().getResource("/img/folder.png")).getImage());
        initComponents();
        this.setLocation(470, 175);
        this.setTitle("Ficheros Java");
        verDatosImpresos.setSize(500, 500);
        verDatosImpresos.setLocation(700, 175);
        verDatosImpresos.setTitle("Datos - Ficheros Secuenciales");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secuencialDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        rutaSecuencialText = new javax.swing.JTextField();
        secuencialEjecutaBtn = new javax.swing.JButton();
        radioLeer = new javax.swing.JRadioButton();
        radioEscribir = new javax.swing.JRadioButton();
        radioSobre = new javax.swing.JRadioButton();
        radioBuscar = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        volverSecuenciaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosNuevosText = new javax.swing.JTextArea();
        secuencialRadioGroup = new javax.swing.ButtonGroup();
        verDatosImpresos = new javax.swing.JDialog();
        datosLabel = new javax.swing.JLabel();
        aleatorioJDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ejecutarAleatorioBtn = new javax.swing.JButton();
        volverAleatorioBtn = new javax.swing.JButton();
        rutaAleatorioText = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosAleatoriosText = new javax.swing.JTextArea();
        crearCosasJDialog = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rutaCrear = new javax.swing.JTextField();
        ficheroRadio = new javax.swing.JRadioButton();
        directorioRadio = new javax.swing.JRadioButton();
        volverCrearCosas = new javax.swing.JButton();
        CrearCosasBtn = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        copiarFicheroJDialog = new javax.swing.JDialog();
        rutaOrigen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rutaDestino = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        ejecutarCopyBtn = new javax.swing.JButton();
        volverBtnCopy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        aleatorioBtn = new javax.swing.JButton();
        secuencialBtn = new javax.swing.JButton();
        copyBtn = new javax.swing.JButton();
        crearBtn = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ficheros Secuenciales");

        secuencialEjecutaBtn.setText("Ejecutar");
        secuencialEjecutaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                secuencialEjecutaBtnMousePressed(evt);
            }
        });

        secuencialRadioGroup.add(radioLeer);
        radioLeer.setText("Leer");

        secuencialRadioGroup.add(radioEscribir);
        radioEscribir.setText("Escribir");

        secuencialRadioGroup.add(radioSobre);
        radioSobre.setText("Sobreescribir");

        secuencialRadioGroup.add(radioBuscar);
        radioBuscar.setText("Buscar");

        volverSecuenciaBtn.setText("Volver");
        volverSecuenciaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverSecuenciaBtnMousePressed(evt);
            }
        });

        datosNuevosText.setColumns(20);
        datosNuevosText.setRows(5);
        jScrollPane1.setViewportView(datosNuevosText);

        javax.swing.GroupLayout secuencialDialogLayout = new javax.swing.GroupLayout(secuencialDialog.getContentPane());
        secuencialDialog.getContentPane().setLayout(secuencialDialogLayout);
        secuencialDialogLayout.setHorizontalGroup(
            secuencialDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(secuencialDialogLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(secuencialEjecutaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(volverSecuenciaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(secuencialDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secuencialDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secuencialDialogLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(secuencialDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rutaSecuencialText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secuencialDialogLayout.createSequentialGroup()
                        .addComponent(radioLeer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioEscribir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioSobre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBuscar)))
                .addGap(70, 70, 70))
        );
        secuencialDialogLayout.setVerticalGroup(
            secuencialDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secuencialDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rutaSecuencialText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(secuencialDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioLeer)
                    .addComponent(radioEscribir)
                    .addComponent(radioSobre)
                    .addComponent(radioBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(secuencialDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secuencialEjecutaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverSecuenciaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        datosLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        datosLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout verDatosImpresosLayout = new javax.swing.GroupLayout(verDatosImpresos.getContentPane());
        verDatosImpresos.getContentPane().setLayout(verDatosImpresosLayout);
        verDatosImpresosLayout.setHorizontalGroup(
            verDatosImpresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verDatosImpresosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );
        verDatosImpresosLayout.setVerticalGroup(
            verDatosImpresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verDatosImpresosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ficheros Aleatorios");

        ejecutarAleatorioBtn.setText("Ejecutar");

        volverAleatorioBtn.setText("Volver");
        volverAleatorioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverAleatorioBtnMousePressed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leer Fichero", "Escribir Fichero", "Tamaño Fichero", "Numero de Registros" }));

        datosAleatoriosText.setColumns(20);
        datosAleatoriosText.setRows(5);
        jScrollPane2.setViewportView(datosAleatoriosText);

        javax.swing.GroupLayout aleatorioJDialogLayout = new javax.swing.GroupLayout(aleatorioJDialog.getContentPane());
        aleatorioJDialog.getContentPane().setLayout(aleatorioJDialogLayout);
        aleatorioJDialogLayout.setHorizontalGroup(
            aleatorioJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(aleatorioJDialogLayout.createSequentialGroup()
                .addGroup(aleatorioJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aleatorioJDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(aleatorioJDialogLayout.createSequentialGroup()
                        .addGroup(aleatorioJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aleatorioJDialogLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(ejecutarAleatorioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(volverAleatorioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(aleatorioJDialogLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(aleatorioJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rutaAleatorioText, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(aleatorioJDialogLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(aleatorioJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))))))
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addContainerGap())
        );
        aleatorioJDialogLayout.setVerticalGroup(
            aleatorioJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aleatorioJDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rutaAleatorioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aleatorioJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ejecutarAleatorioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(volverAleatorioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 32)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Crear Ficheros o Carpetas");

        jLabel6.setText("Nombre:");

        buttonGroup1.add(ficheroRadio);
        ficheroRadio.setText("Fichero");

        buttonGroup1.add(directorioRadio);
        directorioRadio.setText("Directorio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ficheroRadio)
                .addGap(18, 18, 18)
                .addComponent(directorioRadio)
                .addGap(146, 146, 146))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rutaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rutaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ficheroRadio)
                    .addComponent(directorioRadio))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        volverCrearCosas.setText("Volver");
        volverCrearCosas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverCrearCosasMousePressed(evt);
            }
        });

        CrearCosasBtn.setText("Ejecutar");
        CrearCosasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CrearCosasBtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout crearCosasJDialogLayout = new javax.swing.GroupLayout(crearCosasJDialog.getContentPane());
        crearCosasJDialog.getContentPane().setLayout(crearCosasJDialogLayout);
        crearCosasJDialogLayout.setHorizontalGroup(
            crearCosasJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearCosasJDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearCosasJDialogLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(crearCosasJDialogLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(CrearCosasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(volverCrearCosas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crearCosasJDialogLayout.setVerticalGroup(
            crearCosasJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearCosasJDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearCosasJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearCosasBtn)
                    .addComponent(volverCrearCosas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Ruta a copiar:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Ruta donde copiar:");

        ejecutarCopyBtn.setText("Ejecutar");
        ejecutarCopyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ejecutarCopyBtnMousePressed(evt);
            }
        });

        volverBtnCopy.setText("Volver");
        volverBtnCopy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverBtnCopyMousePressed(evt);
            }
        });

        javax.swing.GroupLayout copiarFicheroJDialogLayout = new javax.swing.GroupLayout(copiarFicheroJDialog.getContentPane());
        copiarFicheroJDialog.getContentPane().setLayout(copiarFicheroJDialogLayout);
        copiarFicheroJDialogLayout.setHorizontalGroup(
            copiarFicheroJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copiarFicheroJDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(copiarFicheroJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(copiarFicheroJDialogLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rutaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(copiarFicheroJDialogLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rutaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jSeparator4)
            .addGroup(copiarFicheroJDialogLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(ejecutarCopyBtn)
                .addGap(110, 110, 110)
                .addComponent(volverBtnCopy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        copiarFicheroJDialogLayout.setVerticalGroup(
            copiarFicheroJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copiarFicheroJDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(copiarFicheroJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(copiarFicheroJDialogLayout.createSequentialGroup()
                        .addComponent(rutaOrigen)
                        .addGap(3, 3, 3))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(copiarFicheroJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(copiarFicheroJDialogLayout.createSequentialGroup()
                        .addComponent(rutaDestino)
                        .addGap(3, 3, 3))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(copiarFicheroJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ejecutarCopyBtn)
                    .addComponent(volverBtnCopy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Qué quieres hacer?");

        aleatorioBtn.setText("Fichero Aleatorio");
        aleatorioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aleatorioBtnMousePressed(evt);
            }
        });

        secuencialBtn.setText("Fichero Secuencial");
        secuencialBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                secuencialBtnMousePressed(evt);
            }
        });

        copyBtn.setText("Copiar");
        copyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                copyBtnMousePressed(evt);
            }
        });

        crearBtn.setText("Crear Fichero/Carpeta");
        crearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearBtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secuencialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aleatorioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(copyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(secuencialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aleatorioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(copyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secuencialBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secuencialBtnMousePressed
        secuencialDialog.setIconImage(new ImageIcon(getClass().getResource("/img/folder.png")).getImage());
        secuencialDialog.setVisible(true);
        secuencialDialog.setLocation(470, 175);
        secuencialDialog.setSize(500, 400);
        secuencialDialog.setTitle("Archivo Secuencial - Ficheros Java");
        localizador = 1;
    }//GEN-LAST:event_secuencialBtnMousePressed

    private void secuencialEjecutaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secuencialEjecutaBtnMousePressed
        secuenciales();
    }//GEN-LAST:event_secuencialEjecutaBtnMousePressed

    private void volverSecuenciaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverSecuenciaBtnMousePressed
        volver();
    }//GEN-LAST:event_volverSecuenciaBtnMousePressed

    private void aleatorioBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aleatorioBtnMousePressed
        aleatorioJDialog.setIconImage(new ImageIcon(getClass().getResource("/img/folder.png")).getImage());
        aleatorioJDialog.setVisible(true);
        aleatorioJDialog.setLocation(470, 175);
        aleatorioJDialog.setSize(500, 400);
        aleatorioJDialog.setTitle("Archivo Aleatorio - Ficheros Java");
        localizador = 2;
    }//GEN-LAST:event_aleatorioBtnMousePressed

    private void volverAleatorioBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverAleatorioBtnMousePressed
        volver();
    }//GEN-LAST:event_volverAleatorioBtnMousePressed

    private void crearBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMousePressed
        crearCosasJDialog.setIconImage(new ImageIcon(getClass().getResource("/img/folder.png")).getImage());
        crearCosasJDialog.setVisible(true);
        crearCosasJDialog.setLocation(450, 175);
        crearCosasJDialog.setSize(500, 250);
        crearCosasJDialog.setTitle("Crear Archivos o Directorios - Ficheros Java");
        localizador = 3;
    }//GEN-LAST:event_crearBtnMousePressed

    private void volverCrearCosasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverCrearCosasMousePressed
        volver();
    }//GEN-LAST:event_volverCrearCosasMousePressed

    private void CrearCosasBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCosasBtnMousePressed
        crearCosas();
    }//GEN-LAST:event_CrearCosasBtnMousePressed

    private void copyBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyBtnMousePressed
        copiarFicheroJDialog.setIconImage(new ImageIcon(getClass().getResource("/img/folder.png")).getImage());
        copiarFicheroJDialog.setVisible(true);
        copiarFicheroJDialog.setLocation(450, 175);
        copiarFicheroJDialog.setSize(500, 190);
        copiarFicheroJDialog.setTitle("Copiar Ficheros - Ficheros Java");
        localizador = 4;
    }//GEN-LAST:event_copyBtnMousePressed

    private void volverBtnCopyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverBtnCopyMousePressed
        volver();
    }//GEN-LAST:event_volverBtnCopyMousePressed

    private void ejecutarCopyBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejecutarCopyBtnMousePressed
        copiarFicheros();
    }//GEN-LAST:event_ejecutarCopyBtnMousePressed

    private void copiarFicheros() {
        //declaramos las variables que contienen las rutas de los ficheros que vamos a usar
        String rutaOrigen = this.rutaOrigen.getText();
        String rutaDestino = this.rutaDestino.getText();
        //las rutas las pasamos como parametro para crear ficheros en java
        File origen = new File(rutaOrigen);
        File destino = new File(rutaDestino);
        //si el fichero existe, podemos copiarlo
        if (origen.exists() == true || destino.exists() == true) {
            InputStream fuente = null;
            byte[] buffer = new byte[1024];
            try (OutputStream destinoOK = new FileOutputStream(rutaDestino)) {
                fuente = new FileInputStream(rutaOrigen);
                int leemos;
                //leemos el documento origen 
                while ((leemos = fuente.read(buffer)) != -1) {
                    //escribimos en el documento destino
                    destinoOK.write(buffer, 0, leemos);
                }
                fuente.close();
                JOptionPane.showMessageDialog(null, "Fichero "+rutaOrigen+" copiado con exito.");
                copiarFicheroJDialog.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se ha podido copiar el fichero.");
            }
        }
    }
    
    //llamamos al metodo crearFicheroDirectorio que tenemos a continuacion, se ejecuta al pulsar el boton ejec
    private void crearCosas() {
        try {
            crearFicheroDirectorio();
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*
    Metodo para crear un fichero o un directorio en la ruta indicada.
    */
    private void crearFicheroDirectorio() throws IOException {
        String ruta = rutaCrear.getText(); //guardamos la ruta del fichero/directorio
        /*
        COmo he creado un grupo de radio buttons, en funcion del radio que ha sido seleccionado
        hace una cosa u otra
        */
        
        //directorio, si el directorio con la ruta que le hemos pasado existe salta una alerta
        if (directorioRadio.isSelected()) {
            File directorio = new File(ruta);
            if (directorio.exists()) {
                JOptionPane.showMessageDialog(null, "La carpeta " + directorio.toString() + " ya existe con este nombre.");
            } else {
                //sino, creamos el directorio y hacemos saltar una alerta para saberlo.
                directorio.mkdir();
                JOptionPane.showMessageDialog(null, "La carpeta " + directorio.toString() + " ha sido creada.");
                crearCosasJDialog.setVisible(false);
            }
            //fichero - le pasamos la ruta y si el fichero existe salta la alerta
        } else if (ficheroRadio.isSelected()) {
            File archivo = new File(ruta);
            if (archivo.exists()) {
                JOptionPane.showMessageDialog(null, "El fichero " + archivo.toString() + " ya existe con este nombre.");
            } else {
                //sino creamos el fichero
                archivo.createNewFile();
                JOptionPane.showMessageDialog(null, "El fichero " + archivo.toString() + " ha sido creado.");
                crearCosasJDialog.setVisible(false);
            }
        }
    }
    /*
    metodo para la gestion de ficheros secuenciales, vamos a tener los metodos en funcion del 
    radio button que tengamos pulsado, escribir , sobreescribir, leer y buscar.
    COn interfaz grafica.
    */
    public void secuenciales() {
        String ruta = rutaSecuencialText.getText();
        String datos = datosNuevosText.getText();
        if (radioLeer.isSelected()) {
            String texto = new String();
            try {
                FileReader fr = new FileReader(ruta);
                //buffer de lectura enlazado al puente de comunicacion que es el FileReader
                //FIleReader es el conector entre el fichero y el buffered y este es una copia del archivo con la cual trabajamos
                BufferedReader entrada = new BufferedReader(fr);
                String s;

                // usamos el bucle para meter en en String s todas las lineas del fichero
                // mientras en la linea haya datos (que no sea null)
                while ((s = entrada.readLine()) != null) //texto = texto + s a parte
                {
                    texto += s + "\n";
                }
                verDatosImpresos.setVisible(true);
                datosLabel.setText("\nDatos leidos del archivo con READLINE: \n"
                        + texto);

                //System.out.print((char)entrada.read());
                //cerramos el buffer
                entrada.close();
            } catch (java.io.FileNotFoundException fnfEx) {
                System.out.println("Archivo no encontrado");
                JOptionPane.showMessageDialog(null, "No se ha podido encontrar su archivo o no existe.");
            } catch (java.io.IOException ioex) {
            }
        } else if (radioEscribir.isSelected()){
            try {
            //abro la relacion con el archivo que quiero escribir
            FileWriter fw = new FileWriter(ruta,true); //si pones true escribes detras y si pones false sobrescribes
            //creo una copia del archivo con el que voy a trabajar que apunta a la conexion
            BufferedWriter bw = new BufferedWriter(fw);
            //escribo los datos nuevos y cierro la conexion
            bw.write(datos + "\n");
            bw.close();
            JOptionPane.showMessageDialog(null, "Sus datos han sido escritos en el fichero "+ruta+".");
            datosNuevosText.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se ha podido encontrar su archivo o no existe.");
        }
        } else if (radioSobre.isSelected()){
            try {
            //abro la relacion con el archivo que quiero escribir
            FileWriter fw = new FileWriter(ruta,false); //si pones true escribes detras y si pones false sobrescribes
            //creo una copia del archivo con el que voy a trabajar que apunta a la conexion
            BufferedWriter bw = new BufferedWriter(fw);
            //escribo los datos nuevos y cierro la conexion
            bw.write(datos + "\n");
            bw.close();
            JOptionPane.showMessageDialog(null, "Sus datos han sido sobreescritos en el fichero "+ruta+".");
            datosNuevosText.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se ha podido encontrar su archivo o no existe.");
        }
        }else {
            String texto = new String();
        try {
            FileReader fr = new FileReader(ruta);
            BufferedReader entrada = new BufferedReader(fr);
            System.out.println("Conectada");
            String palabraABuscar = datosNuevosText.getText();
            String linea = "";
            palabraABuscar = datosNuevosText.getText();
            while ((linea = entrada.readLine()) != null) {
               texto += linea + "\n";
                if (linea.indexOf(palabraABuscar) != -1) {
                    int posChar = texto.indexOf(linea.substring(0,1));
                    verDatosImpresos.setVisible(true);
                    datosLabel.setText("Se encontro la palabra: \t" +linea + "\n en la posición " + posChar);
                }   
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se ha podido encontrar su archivo o no existe.");
        }
        }
    }
    
//    public static void accederAlComboBox(String fichero, String item, String ruta) {
//        switch (item) {
//            case "Leer Datos":
//                ;
//                    break;
//                
//        
//        }
//    }
//    
//    private void aleatorio(){
//        String ruta = rutaAleatorioText.getText();
//        String datos = datosAleatoriosText.getText();
//        String item = jComboBox1.getSelectedItem().toString();
//        accederAlComboBox(ruta, item, ruta);
//    }
    
    private void volver(){
        switch (localizador) {
            case 1 : secuencialDialog.setVisible(false);break;
            case 2 : aleatorioJDialog.setVisible(false);break;
            case 3 : crearCosasJDialog.setVisible(false);break;
            case 4 : copiarFicheroJDialog.setVisible(false);break;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton CrearCosasBtn;
    private javax.swing.JButton aleatorioBtn;
    private javax.swing.JDialog aleatorioJDialog;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog copiarFicheroJDialog;
    private javax.swing.JButton copyBtn;
    private javax.swing.JButton crearBtn;
    private javax.swing.JDialog crearCosasJDialog;
    private javax.swing.JTextArea datosAleatoriosText;
    private javax.swing.JLabel datosLabel;
    public static javax.swing.JTextArea datosNuevosText;
    public static javax.swing.JRadioButton directorioRadio;
    private javax.swing.JButton ejecutarAleatorioBtn;
    private javax.swing.JButton ejecutarCopyBtn;
    public static javax.swing.JRadioButton ficheroRadio;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton radioBuscar;
    private javax.swing.JRadioButton radioEscribir;
    private javax.swing.JRadioButton radioLeer;
    private javax.swing.JRadioButton radioSobre;
    private javax.swing.JTextField rutaAleatorioText;
    public static javax.swing.JTextField rutaCrear;
    private javax.swing.JTextField rutaDestino;
    private javax.swing.JTextField rutaOrigen;
    private javax.swing.JTextField rutaSecuencialText;
    private javax.swing.JButton secuencialBtn;
    public static javax.swing.JDialog secuencialDialog;
    private javax.swing.JButton secuencialEjecutaBtn;
    private javax.swing.ButtonGroup secuencialRadioGroup;
    public static javax.swing.JDialog verDatosImpresos;
    private javax.swing.JButton volverAleatorioBtn;
    private javax.swing.JButton volverBtnCopy;
    public static javax.swing.JButton volverCrearCosas;
    private javax.swing.JButton volverSecuenciaBtn;
    // End of variables declaration//GEN-END:variables
}
